sonar.projectKey=sonar-node-app
sonar.projectName=Sonar Node App
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_6a0f04e9f4778411090ef4269b216c67e2ef4f11
